# Generated by Django 5.0.1 on 2024-02-17 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('imageURL', models.CharField(max_length=200, null=True)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('originalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lowestPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('highestPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('averagePrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('isOutOfStock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='myapp.product')),
            ],
            options={
                'unique_together': {('product', 'date')},
            },
        ),
    ]
